# Generated by Django 2.0.7 on 2018-08-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextends',
            name='vip',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата по которую пользователь имеет ВИП-статус'),
        ),
    ]
