# Generated by Django 2.0.7 on 2018-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cost', models.FloatField(default=0.0)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('available', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'New product'), (1, 'Subscription')], default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
