# Generated by Django 2.0.7 on 2018-07-23 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ИД для поста', primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Введите текст', max_length=4000)),
                ('post_data', models.DateTimeField(auto_now_add=True, help_text='Дата публикации')),
                ('modify_data', models.DateTimeField(auto_now=True, help_text='Дата редактирования')),
                ('status', models.CharField(blank=True, choices=[('d', 'Deleted'), ('a', 'Active'), ('h', 'Hidden')], default='a', help_text='Статус поста', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
