# Generated by Django 2.0.7 on 2018-08-01 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modify_data',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_data',
            new_name='post_date',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
