# Generated by Django 2.0.7 on 2018-08-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postimages_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'ordering': ['order']},
        ),
    ]
