# Generated by Django 2.0.7 on 2018-08-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_uuidtaggeditem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uuidtaggeditem',
            name='user',
        ),
    ]
